version: '2'
services:
  db:
    image: postgres:16
    container_name: ds-postgres
    user: root
    environment:
      - POSTGRES_USER=amaaiza
      - POSTGRES_PASSWORD=mysecretpassword
      - POSTGRES_DB=piscineds
    restart: always      
    ports:
      - 5432:5432
    volumes:
        - ./postgresql:/var/lib/postgresql/data

  
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: pg@pg.com
      PGADMIN_DEFAULT_PASSWORD: pgadmin
    ports:
      - 5050:80
    depends_on:
      - db
    volumes:
      - ./pgadmin/var/lib/pgadmin:/var/lib/pgadmin